Update code owners list
l3af-project/l3afd pull request #257
Opened 2023-06-29 13:08 UTC by sanfern

This PR is to add Ajay to the code reviewer list.

2023-06-29 14:22 UTC, jniesz requested changes
Why is Ajay's username strcloud?  This is not clear to me and he should have a normal user name and not use a username that at a time meant something different internally.

2023-07-11 15:09 UTC, dthaler submitted a review, later dismissed

2023-07-12 07:39 UTC, ajayR006 commented
> Why is Ajay's username strcloud? This is not clear to me and he should have a normal user name and not use a username that at a time meant something different internally.

Username is changed to ajayR006 now.

2023-07-31 02:24 UTC, dthaler commented on CODEOWNERS
> +* @sanfern @charleskbliu0 @jniesz @dthaler @strcloud
This needs to be updated now

2023-08-01 14:12 UTC, jniesz approved these changes

2023-08-01 15:03 UTC, dthaler approved these changes

2023-08-01 15:03 UTC, merged