Creating a  workflow for End 2 End testing
l3af-project/l3afd pull request #280
Opened 2023-09-19 04:19 UTC by Atul-source

here I will be creating a separate flow for E2E testing

2023-09-27 18:11 UTC, dthaler commented on kf/kfdebug.go
> +		log.Info().Msg("Starting KF debug server")
We should not use the term "KF" anywhere.

2023-10-08 00:43 UTC, dthaler approved these changes

2023-10-09 11:31 UTC, sanfern approved these changes

2023-10-29 14:24 UTC, sanfern requested changes

2023-10-29 14:24 UTC, sanfern commented on .github/workflows/ci-e2e.yaml
> +          limactl shell bpfdev exec -- sudo git clone -b E2E https://github.com/Atul-source/l3af-arch.git
Remove your fork reference

2023-11-02 10:52 UTC, closed without merging