L3AFD metric for ebpf program update command failure count
l3af-project/l3afd pull request #283
Opened 2023-09-25 07:40 UTC by Atul-source

A new metric is added to track Update failures of eBPF Function. This PR fixes the issue reported in [#282](https://github.com/l3af-project/l3afd/issues/282)

2023-09-25 21:07 UTC, sanfern approved these changes
LGTM

2023-09-26 15:39 UTC, dthaler commented on stats/metrics.go
> +			Help:      "The count of Failed network functions updates",
Don't use the term "network function"

2023-09-26 15:39 UTC, dthaler requested changes

2023-09-26 15:39 UTC, dthaler commented on stats/metrics.go
> +		[]string{"host", "ebpf_program", "direction", "interface_name"},
why "ebpf_program" instead of "bpf_program"?

2023-10-03 15:09 UTC, dthaler approved these changes

2023-10-04 09:02 UTC, sanfern approved these changes
LGTM

2023-10-04 09:03 UTC, merged