Running L3AFD in a Docker container
l3af-project/l3afd pull request #395
Opened 2024-05-29 11:27 UTC by aka320

Changes
---------
- Added Dockerfile to build the Docker image for L3AFD
- Update README with the instructions to build L3AFD Docker image and run it in a Container

Testing
-------
- Able to attach XDP and TC programs using L3AFD Container

2024-05-29 14:20 UTC, pmoroney approved these changes
LGTM, although it does sound like a good idea to pin the hash for the docker file as suggested by the security bot.

2024-05-29 16:39 UTC, sanfern requested changes

2024-05-29 16:39 UTC, sanfern commented on README.md
> +# Build L3AFD Docker image
Move this block in building section

2024-05-29 16:39 UTC, sanfern commented on build-docker/Dockerfile
> +            libjson-c-dev \
Fix alignment.

2024-06-05 16:32 UTC, sanfern approved these changes
LGTM

2024-06-05 16:34 UTC, charleskbliu0 approved these changes
Looks good

2024-06-05 16:34 UTC, merged