L3AFd Docker build CI integration
l3af-project/l3afd pull request #410
Opened 2024-06-19 12:04 UTC by aka320

Building the Docker image and uploading it to Artifactory as part of CI build.

2024-06-19 16:20 UTC, sanfern requested changes
Can we explore to upload the image to docker hub?

2024-06-19 16:20 UTC, sanfern commented on .github/workflows/ci-build.yaml
> +          path: l3afd-docker-img-linux-x86_64-r2-latest.tar
```suggestion
          path: l3afd-docker-img-linux-x86_64-v2.0.0.tar
```

2024-06-19 16:20 UTC, sanfern commented on .github/workflows/ci-build.yaml
> +          sudo docker save l3afd:r2-latest > l3afd-docker-img-r2-latest.tar
```suggestion
          sudo docker save l3afd-docker-img-linux-x86_64-v2.0.0.tar
```

2024-06-19 16:20 UTC, sanfern commented on .github/workflows/ci-build.yaml
> +          sudo cp /root/l3af-arch/dev_environment/cfg/l3afd.cfg ./build-docker
Avoid cloning of l3af-arch repo, its better to have local copy of l3afd.cfg file here.

2024-06-24 17:22 UTC, pmoroney commented on config/l3afd.cfg
> +enabled: false
Is this file used for other use-cases, or as an example config for users? If so we might want to consider these changes and make sure this is what we want users to use by default.

2024-06-26 09:32 UTC, sanfern requested changes
Please update l3afd.cfg file to the latest, like tc_ingress_root.bpf.o and tc_egress_root.bpf.o

2024-06-26 09:32 UTC, sanfern commented on config/l3afd.cfg
>  object-file: xdp_root_kern.o
```suggestion
object-file: xdp_root.bpf.o
```

2024-06-26 16:29 UTC, sanfern requested changes

2024-06-26 16:29 UTC, sanfern commented on README.md
> +docker build -t l3afd:r2 -f Dockerfile .
```suggestion
docker build -t l3afd:v2.0.0 -f Dockerfile .
```
we need to change this version to v2.0.1 on the day of release.

2024-06-27 05:38 UTC, sanfern commented
@aka320 Please rebase your branch with latest main.

2024-06-27 06:31 UTC, closed without merging